target: #目标名称
	g++ echo_server.cpp -o echo_server -lws2_32 -std=c++14


#目标依赖


# OBJC = main.o print.o
# SRCS := $(shell find ./* -type f | grep "\.cpp")
# ${warning SRCH IS $(SRCS)}
# target:main.o print.o
# 	g++ ${OBJC} -o main
# main.o:
# 	g++ -c main.cpp -o main.o
# print.o:
# 	g++ -c print.cpp -I. -o print.o 
# %.o: %.cpp
# 	g++ -I. -c $< -o $@
# clean:
# 	rm -rf $(OBJC) main.exe
# %.o %.cpp 表示所有的.o文件都是有相同名称的.cpp文件编译而成
# <:表示所有依赖的挨个值.cpp
# @:表示所有的目标的挨个值.o
# := 是覆盖之前的值
# ?= 是如果没有被赋值过就赋予等号后面的值


# Makefile高级用法->文件过滤

